[build]
  command = "npm run build"
  functions = "netlify/functions"
  publish = ".next"


[[plugins]]
  package = "netlify-plugin-cypress"

[functions]
        node_bundler = "esbuild"

[dev]
  port = 8888 
  targetPort = 3000 
  autoLaunch = true