[build]
  command = "npm run build"
  functions = ".netlify/functions"
  publish = ".next"


[[plugins]]
  package = "netlify-plugin-cypress"

[dev]
  port = 8888 
  targetPort = 3000 
  autoLaunch = true